### ISSUE TITLE
Switching Models isn't taking effect.

### ISSUE THREAD

**Issue by orsenthil** [aws-samples/amazon-bedrock-client-for-mac#34] opened 2024-06-20 22:53 UTC
**Describe the bug**
I tried to switch from default claude model to a different model to chat.

- It continues using old model.
- Sometimes application crashes

**Comment by didhd** [comment] 2024-06-29 17:13
@orsenthil Thank you for your report. The behavior you experienced is actually the intended functionality. For consistency and to prevent potential confusion, the application does not allow switching between models mid-conversation. The selected model will be used for the entire chat session. If you need to use a different model, you will have to start a new conversation.

Since this is working as designed and not a bug, I am closing this issue. However, we appreciate you taking the time to provide feedback, as it helps us understand how users interact with the application and identify potential areas for improvement in future updates.

**Closed by didhd** 2024-06-29 17:13 UTC
Labels: wontfix
