### ISSUE TITLE
[BUG] Didn't work

### ISSUE THREAD

**Issue by minorun365** [aws-samples/amazon-bedrock-client-for-mac#62] opened 2024-12-21 08:36 UTC
Installed this and invoked, but it didn't work.

![スクリーンショット 2024-12-21 17 33 20](https://github.com/user-attachments/assets/a65b890b-1c15-453f-a07b-da06b33f4c77)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Environment (required):**
 - macOS version: [e.g. 13.0]
 - Amazon Bedrock Client for Mac version: [e.g. 1.0.0]

**Log Files (optional)**
Please attach the log files located in `~/Amazon Bedrock Client/logs/`. These logs are crucial for diagnosing the issue.

**Screenshots (optional)**

**Additional context (optional)**

**Comment by didhd** [comment] 2024-12-22 06:50
Closing this issue as it's a duplicate of #60. The Nova model is supported in version 1.2.6 of Amazon Bedrock Client for Mac. Please update to the latest version to use Nova.

I'm marking this as duplicate since the same issue and solution have already been addressed in https://github.com/aws-samples/amazon-bedrock-client-for-mac/issues/60.

For reference, you'll need to be on version 1.2.6 or higher to use the Nova model. Let me know if you have any questions after upgrading.

/close

**Closed by didhd** 2024-12-22 06:50 UTC
Labels: bug
